package imagedb

/**
 * ImageAsset is the domain model for an image in the system.
 * The original data will be stored in a folder structure matching the assets dateCreated date: {storage}/originals/{yyyy}/{MM}/{dd}/{name}
 * Versions generated by the system will be stored in: {storage}/generated/{yyyy}/{MM}/{dd}/{name}/{pixelWidth}x{pixelHeight}.jpg
 */

class ImageAsset {

    Author author

    Set<Tag> tags
    Set<Metadata> metadata
    String filename

    String heading
    String description

    String place
    String city
    String country
    BigDecimal latitude
    BigDecimal longitude

    Long filesize = 0
    Integer pixelWidth = 0
    Integer pixelHeight = 0

    Date dateTimeOriginal
    TimeZone timeZoneOriginal

    Boolean enabled = true
    Date dateCreated

    static constraints = {
        filename blank: false
        heading nullable: true
        description nullable: true
        place nullable: true
        city nullable: true
        country nullable: true
        latitude nullable: true
        longitude nullable: true
        pixelHeight nullable: true
        pixelWidth nullable: true
        dateTimeOriginal nullable: true
        timeZoneOriginal nullable: true
    }

    static mapping = {
        description type: 'text'
    }
}
